name: multisig-test

on:
  workflow_dispatch:
  pull_request:
    branches: [develop, master]

jobs:
  test:
    runs-on: [self-hosted, graffino]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
        if: always()

      - name: Checkout
        id: Checkout
        uses: actions/checkout@master
        with:
          ref: 'develop'
        if: success()

      - uses: nightstory/replace-env@v1
        id: create-env
        env:
          GH_ACCESS_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
          UNIQUE_CONTRACT_ADDRESS: "${{ secrets.UNIQUE_CONTRACT_ADDRESS }}"
          UNIQUE_CONTRACT_NAME: "${{ secrets.UNIQUE_CONTRACT_NAME }}"
          GOOGLE_ANALYTICS_KEY: "${{ secrets.GOOGLE_ANALYTICS_KEY_DEVNET }}"
        with:
          input_file: .env.template
          output_file: .env
          pattern: double_underscore

      - name: Config setup
        run: |
          make setup-wallet

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: YARN Install
        id: YARN-Install
        if: success()
        run: yarn --network-timeout 500000

      # - name: Lint
      #   id: Lint
      #   if: success()
      #   run: |
      #     yarn lint

      - name: Build
        id: Build
        if: success()
        run: |
          export NODE_OPTIONS="--max-old-space-size=2048"
          export CI=false
          export DISABLE_ESLINT_PLUGIN=true
          yarn build

      - uses: act10ns/slack@v1.2.2
        if: always()
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
